### ISSUE TITLE
Getting crash block invoke

### ISSUE THREAD

**Issue by ricky1550** [abpopov/SocketCluster-ios-client#4]
Here is the details of crash
0x100e46d38 __30-[SCSocket WSConnectedHandler]_block_invoke (SCSocket.m:327)
3  SocketCluster_ios_client       0x100e4741c -[SCSocket WSMessageHandler:] (SCSocket.m:422)
4  SocketRocket                   0x100e62f48 __30-[SRWebSocket _handleMessage:]_block_invoke (SRWebSocket.m:839)

Line number can change by 2 or 3 numbers.

**Comment by abpopov** [comment]
Can you reproduce this crash?
It's caused by data sent from server. 
422 line is   id responseData =[dictionary objectForKey:@"data"] ;

I think that dictionary in null

**Comment by ricky1550** [comment]
Yes i reproduced the crash, actually it was due to the lost reference of the SocketClusterDelegate when any event is received. And also i was able to fix it by changing the delegate type to WEAK.
@property (weak, nonatomic,nullable) id <SocketClusterDelegate>delegate.
